name: Sincronizzazione Automatica Prodotti

on:
  schedule:
    # Gira automaticamente ogni giorno alle 4 del mattino
    - cron: '0 4 * * *'
  workflow_dispatch: # Ti permette di avviarlo a mano con un click

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    # Aggiornato da v3 a v4 (Supporta Node 24 nativo)
    - name: Accedi alla Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # Aggiornato da v4 a v5 (Supporta Node 24 nativo)
    - name: Configura Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installa Librerie
      run: |
        pip install requests pandas

    - name: Esegui lo Script di Fetch Prodotti
      run: python aggiorna_dati.py

    - name: Salva le modifiche su GitHub
      run: |
        git config --global user.name 'InciarmoBot'
        git config --global user.email 'bot@inciarmo.local'
        git add prodotti.csv
        git commit -m "Aggiornamento automatico prodotti da API" || exit 0
        git push
