name: Aggiornamento Dati Inciarmo Spesa

on:
  schedule:
    # Esegue la pipeline ogni giorno alle 3 del mattino
    - cron: '0 3 * * *'
  workflow_dispatch:
    # Permette di avviare la pipeline manualmente dall'interfaccia di GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # Ottimizza i tempi di build riutilizzando la cache delle librerie

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas beautifulsoup4 lxml

    - name: Run pipeline
      run: python aggiorna_dati.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "InciarmoSpesaBot"
        git config --global user.email "bot@inciarmospesa.local"
        # Controlla se ci sono modifiche nei file prodotti.csv o prodotti_raw.csv prima di fare il push
        if [[ -n "$(git status --porcelain)" ]]; then
          git add prodotti.csv prodotti_raw.csv
          git commit -m "Aggiornamento automatico database prodotti e prezzi live"
          git push
        else
          echo "Nessun nuovo dato o variazione di prezzo rilevata."
        fi
